spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ma-ville-et-moi-database?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
